### ISSUE TITLE
Exception error related to file copy

### ISSUE THREAD

**Issue by cmg-divined** [DurtyFree/altv-cloth-tool#2]
I have the following error:
System.ArgumentNullException: File name cannot be null.
Parameter name: sourceFileName
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at AltTool.ResourceBuilder.BuildResourceFiveM(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\AltTool\ResourceBuilder.cs:line 766
   at AltTool.ProjectBuild.BuildButton_Click(Object sender, RoutedEventArgs e) in H:\DevProjects\GIT_Projects\altv-cloth-tool\AltTool\ProjectBuild.xaml.cs:line 60

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Fixed in latest release, V1.2
