### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by xewier** [DurtyFree/altv-cloth-tool#22]
I have the following error:
System.ArgumentException: Illegal characters in path.
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at altClothTool.App.Builders.AltvResourceBuilder.CopyClothTextureToResource(String clothTextureFilePath, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String ytdPostfix, Char offsetLetter) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\AltvResourceBuilder.cs:line 63
   at altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:line 56
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 18

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

Tried different outputs in different places, always error, I started getting it today (2021. 07. 14.), and I always used the same output place, not error.

**Comment by DurtyFree** [comment]
Place input files in different folder or select different output folders. 
Path seems to contain illegal characters.

**Comment by xewier** [comment]
fixed
