### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by xewier** [DurtyFree/altv-cloth-tool#24]
I have the following error:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RageLib.Data.PartialStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(Stream stream)
   at RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(String fileName)
   at altClothTool.App.Builders.SingleplayerResourceBuilder.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\SingleplayerResourceBuilder.cs:line 244
   at altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:line 23

**Comment by DurtyFree** [comment]
Your clothes project is too big, it runs out of memory.

This is a known issue that will likely not be fixed, split your clothes project.

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
